const FilterActionTypes = {
    SET_FILTER_COLOR: 'SET_FILTER_COLOR',
    SET_FILTER_SIZE: 'SET_FILTER_SIZE',
    SET_FILTER_SEASON: 'SET_FILTER_SEASON',
    SET_FILTER_MATERIAL: 'SET_FILTER_MATERIAL',
    SET_FILTER_PRICE: 'SET_FILTER_PRICE',
}

export default FilterActionTypes;