const PRODUCTS_DATA = [
            //BLAZERS

        {
            id: '1',
            productName: 'Пиджак Boss Johnstons',
            category: 'blazers',
            imageLinks: ['/images/clothing/blazers/01/MP002XM0N6F3_8927555_1_v2_2x.jpg',
                         '/images/clothing/blazers/01/MP002XM0N6F3_8943309_2_v1_2x.jpg',
                         '/images/clothing/blazers/01/MP002XM0N6F3_8943310_3_v1_2x.jpg',
                         '/images/clothing/blazers/01/MP002XM0N6F3_8943311_4_v1_2x.jpg'],
            price: 39990,
            sizes: ['48', '50', '52','54','58'],
            color: ['синий'],
            material: ['Шерсть'],
            season: 'мульти',
            description: 'Пиджак от премиального бренда выполнен из тонкого шерстяного текстиля, гладкая подкладка. Особенности: приталенного кроя, застежка на пуговицы, боковые и нагрудный карманы, поролоновые подплечники.'

        }, 
        {
            id: '2',
            productName: 'Пиджак Hugo',
            category: 'blazers',
            imageLinks: ['/images/clothing/blazers/02/MP002XM0UZNW_8927568_1_v2_2x.jpg',
                        '/images/clothing/blazers/02/MP002XM0UZNW_8943348_2_v1_2x.jpg',
                        '/images/clothing/blazers/02/MP002XM0UZNW_8943349_3_v1_2x.jpg',
                        '/images/clothing/blazers/02/MP002XM0UZNW_8943350_4_v1_2x.jpg'],
            price: 12555,
            sizes: ['48', '50', '52','54'],
            color: ['черный'],
            material: ['Полиэстер', 'Вискоза', 'Эластан'],
            season: 'мульти',
            description: 'Пиджак от премиального бренда выполнен из текстиля. Модель приталенного кроя. Особенности: застежка на пуговицу, два боковых кармана, воротник с лацканами, текстильная подкладка.'

        }, 
        {
            id: '3',
            productName: 'Пиджак Seventy',
            category: 'blazers',
            imageLinks: ['/images/clothing/blazers/03/SE049EMHZFA0_11109021_1_v1_2x.jpg',
                         '/images/clothing/blazers/03/SE049EMHZFA0_11109022_2_v1_2x.jpg',
                         '/images/clothing/blazers/03/SE049EMHZFA0_11109023_3_v1_2x.jpg',
                         '/images/clothing/blazers/03/SE049EMHZFA0_11109024_4_v1_2x.jpg'],
            price: 13336,
            sizes: ['52','54'],
            color: ['синий'],
            material: ['Хлопок', 'Эластан'],
            season: 'мульти',
            description: 'Пиджак от премиального бренда выполнен из тонкого шерстяного текстиля, гладкая подкладка. Особенности: приталенного кроя, застежка на пуговицы, боковые и нагрудный карманы, поролоновые подплечники.'

        },   
        {
            id: '4',
            productName: 'Пиджак Sand',
            category: 'blazers',
            imageLinks: ['/images/clothing/blazers/04/SA915EMHLGF3_10848163_1_v1_2x.jpg',
                         '/images/clothing/blazers/04/SA915EMHLGF3_10848164_2_v1_2x.jpg',
                         '/images/clothing/blazers/04/SA915EMHLGF3_10848165_3_v1_2x.jpg',
                         '/images/clothing/blazers/04/SA915EMHLGF3_10848166_4_v1_2x.jpg'],
            price: 20555,
            sizes: ['48', '50', '52','54', '58'],
            color: ['синий'],
            material: ['Лен'],
            season: 'мульти',
            description: 'Пиджак от премиального бренда выполнен из льняного текстиля. Особенности: отложной воротник с лацканами, застежка на пуговицы, три втачных кармана, внутри два кармана, две шлицы на спинке.'

        },  
        {
            id: '5',
            productName: 'Пиджак Ted Baker London',
            category: 'blazers',
            imageLinks: ['/images/clothing/blazers/05/TE019EMHRQZ2_10671914_1_v1_2x.jpg',
                         '/images/clothing/blazers/05/TE019EMHRQZ2_10671915_2_v1_2x.jpg',
                         '/images/clothing/blazers/05/TE019EMHRQZ2_10671916_3_v1_2x.jpg',
                         '/images/clothing/blazers/05/TE019EMHRQZ2_10671917_4_v1_2x.jpg'],
            price: 20300,
            sizes: ['54'],
            color: ['синий'],
            material: ['Полиэстер', 'Вискоза', 'Эластан'],
            season: 'мульти',
            description: 'Пиджак выполнен из смесового текстиля с яркой подкладкой. Модель приталенного силуэта. Детали: английский воротник, застежка на пуговицах, три карман снаружи и два кармана внутри, шлица.'

        },  
        {
            id: '6',
            productName: 'Пиджак Hackett London',
            category: 'blazers',
            imageLinks: ['/images/clothing/blazers/06/HA024EMHMHT8_11083184_1_v1_2x.jpg',
                         '/images/clothing/blazers/06/HA024EMHMHT8_11083185_2_v1_2x.jpg',
                         '/images/clothing/blazers/06/HA024EMHMHT8_11083186_3_v1_2x.jpg',
                         '/images/clothing/blazers/06/HA024EMHMHT8_11083187_4_v1_2x.jpg'],
            price: 20636,
            sizes: ['48', '50', '52','54', '58'],
            color: ['голубой'],
            material: ['Лен'],
            season: 'мульти',


        },  

        //COATS

        {
            id: '7',
            productName: 'Пальто Hugo',
            category: 'coats',
            imageLinks: ['/images/clothing/coats/01/MP002XM12CCJ_11406378_1_v1_2x.jpg',
                         '/images/clothing/coats/01/MP002XM12CCJ_11406379_2_v1_2x.jpg',
                         '/images/clothing/coats/01/MP002XM12CCJ_11406380_3_v1_2x.jpg',
                         '/images/clothing/coats/01/MP002XM12CCJ_11406381_4_v1_2x.jpg'],
            price: 45000,
            sizes: ['48', '50', '52','54','58'],
            color: ['черный'],
            material: ['Шерсть', 'Кашемир'],
            season: 'демисезон',
            description: 'Пальто выполнено из мягкого драпа. Особенности: застежка на пуговицы, два внешних кармана, гладкая текстильная подкладка, воротник с лацканами, шлица.'

        }, 
        {
            id: '8',
            productName: 'Пальто Bazioni',
            category: 'coats',
            imageLinks: ['/images/clothing/coats/02/MP002XM23ZVQ_7698023_1_v1.jpg',
                         '/images/clothing/coats/02/MP002XM23ZVQ_7698024_2_v1.jpg',
                         '/images/clothing/coats/02/MP002XM23ZVQ_7698025_3_v1.jpg',
                         '/images/clothing/coats/02/MP002XM23ZVQ_7698026_4_v1.jpg'],
            price: 20000,
            sizes: ['48', '50', '52','54','58'],
            color: ['серый'],
            material: ['Шерсть'],
            season: 'демисезон',
            description: 'Пальто мужское  двубортное с застежкой на пуговицы. Модель утеплена термоплюс 100 г. Детали: на полочках- верхний нагрудный карман с листочкой, два нижних боковых накладных кармана с клапанами'

        }, 
        {
            id: '9',
            productName: 'Полупальто Absolutex',
            category: 'coats',
            imageLinks: ['/images/clothing/coats/03/MP002XM1Q0NE_10403084_1_v1_2x.jpg',
                         '/images/clothing/coats/03/MP002XM1Q0NE_10403085_2_v1_2x.jpg',
                         '/images/clothing/coats/03/MP002XM1Q0NE_10403086_3_v1_2x.jpg',
                         '/images/clothing/coats/03/MP002XM1Q0NE_10403087_4_v1_2x.jpg'],
            price: 15990,
            sizes: ['46', '48', '50', '52','54','56'],
            color: ['черный'],
            material: ['Шерсть'],
            season: 'демисезон',
            description: 'Полупальто выполнено из шерстяного текстиля, искусственный утеплитель термоплюс 100 г. Модель прямого кроя. Детали: воротник-стойка, застежка на пуговицы, длинные рукава, 2 внешних кармана, 1 внутренний карман.'            

        }, 
        {
            id: '10',
            productName: 'Пальто Bazioni',
            category: 'coats',
            imageLinks: ['/images/clothing/coats/04/MP002XM1K3DB_9466474_1_v1_2x.jpg',
                         '/images/clothing/coats/04/MP002XM1K3DB_9466475_2_v1_2x.jpg',
                         '/images/clothing/coats/04/MP002XM1K3DB_9466476_3_v1_2x.jpg',
                         '/images/clothing/coats/04/MP002XM1K3DB_9466477_4_v1_2x.jpg'],
            price: 19550,
            sizes: ['48', '50', '52','54','58'],
            color: ['серый'],
            material: ['Шерсть'],
            season: 'демисезон',
            description: 'Пальто выполнено из шерстяного материала с гладкой подкладкой. Модель приталенного силуэта. Детали: воротник-стойка, застежка на пуговицах, шлица, пять карманов снаружи и два кармана внутри.'

        }, 
        {
            id: '11',
            productName: 'Пальто Absolutex',
            category: 'coats',
            imageLinks: ['/images/clothing/coats/05/MP002XM24RTV_11212640_1_v1_2x.jpg',
                         '/images/clothing/coats/05/MP002XM24RTV_11212641_2_v1_2x.jpg',
                         '/images/clothing/coats/05/MP002XM24RTV_11212642_3_v1_2x.jpg',
                         '/images/clothing/coats/05/MP002XM24RTV_11212643_4_v1_2x.jpg'],
            price: 17500,
            sizes: ['48', '50', '52','54','56','58'],
            color: ['черный'],
            material: ['Шерсть'],
            season: 'демисезон',
            description: 'Пальто выполнено из мягкого драпа. Детали: застежка на пуговицы, два внешних кармана, гладкая текстильная подкладка, воротник с лацканами.'

        }, 
        {
            id: '12',
            productName: 'Пальто Bazioni',
            category: 'coats',
            imageLinks: ['/images/clothing/coats/06/MP002XM2434F_7829518_1_v1.jpg',
                         '/images/clothing/coats/06/MP002XM2434F_7829519_2_v1.jpg',
                         '/images/clothing/coats/06/MP002XM2434F_7829520_3_v1.jpg',
                         '/images/clothing/coats/06/MP002XM2434F_7829521_4_v1.jpg'],
            price: 17050,
            sizes: ['46', '52','54','56'],
            color: ['синий'],
            material: ['Шерсть'],
            season: 'демисезон',
            description: 'Пальто выполнено из шерстяного материала с гладкой подкладкой и искусственным утеплителем. Модель прямого силуэта. Детали: отложной воротник, застежка на молнию и ветрозащитный клапан с пуговицами, четыре кармана снаружи и два кармана внутри, шлица.'

        }, 
        {
            id: '13',
            productName: 'Пальто Zadig & Voltaire',
            category: 'coats',
            imageLinks: ['/images/clothing/coats/07/ZA016EMGNGA1_10190817_1_v1_2x.jpg',
                         '/images/clothing/coats/07/ZA016EMGNGA1_10190818_2_v1_2x.jpg',
                         '/images/clothing/coats/07/ZA016EMGNGA1_10190819_3_v1_2x.jpg',
                         '/images/clothing/coats/07/ZA016EMGNGA1_10190820_4_v1_2x.jpg'],
            price: 22000,
            sizes: ['50', '52'],
            color: ['синий'],
            material: ['Шерсть', 'Полиэстер', 'Полиамид '],
            season: 'демисезон',
            description: 'Пальто от премиального бренда выполнено из шерстяного текстиля. Модель прямого кроя. Особенности: воротник с лацканами, застежка на пуговицы, длинные рукава, три внешних и два внутренних кармана, шлица, гладкая подкладка.'

        }, 

        //POLO

        {
            id: '14',
            productName: 'Поло Trussardi',
            category: 'polo',
            imageLinks: ['/images/clothing/polo/01/TR002EMIHNW6_10998506_1_v1_2x.jpg',
                         '/images/clothing/polo/01/TR002EMIHNW6_10998507_2_v1_2x.jpg',
                         '/images/clothing/polo/01/TR002EMIHNW6_10998508_3_v1_2x.jpg',
                         '/images/clothing/polo/01/TR002EMIHNW6_10998509_4_v1_2x.jpg'],
            price: 22600,
            sizes: ['46', '48', '50'],
            color: ['коричневый'],
            material: ['Хлопок'],
            season: 'мульти',
            description: 'Поло от премиум-бренда выполнено из хлопкового трикотажа. Особенности: прямой крой, отложной воротник, застежка на пуговицы до середины груди.'

        },
        {
            id: '15',
            productName: 'Поло Polo Ralph Lauren',
            category: 'polo',
            imageLinks: ['/images/clothing/polo/02/MP002XM052HE_11331464_1_v1_2x.jpg',
                         '/images/clothing/polo/02/MP002XM052HE_11331465_2_v1_2x.jpg',
                         '/images/clothing/polo/02/MP002XM052HE_11331466_3_v1_2x.jpg',
                         '/images/clothing/polo/02/MP002XM052HE_11331467_4_v1_2x.jpg'],
            price: 12000,
            sizes: ['48'],
            color: ['черный'],
            material: ['Хлопок'],
            season: 'мульти',
            description: 'Поло от премиум-бренда выполнено из хлопкового трикотажа. Особенности: отложной воротник, укороченная застежка на пуговицах, вышивка, разрезы.'

        },
        {
            id: '16',
            productName: 'Поло Aeronautica Militare',
            category: 'polo',
            imageLinks: ['/images/clothing/polo/03/AE003EMHOVR0_10548704_1_v1_2x.jpg',
                         '/images/clothing/polo/03/AE003EMHOVR0_10548705_2_v1_2x.jpg',
                         '/images/clothing/polo/03/AE003EMHOVR0_10548706_3_v1_2x.jpg',
                         '/images/clothing/polo/03/AE003EMHOVR0_10548707_4_v1_2x.jpg'],
            price: 9000,
            sizes: ['50'],
            color: ['хаки'],
            material: ['Хлопок'],
            season: 'мульти',
            description: 'Поло от премиум-бренда выполнено из хлопка. Особенности: отложной воротник; застежка на три пуговицы; короткие рукава.'

        },
        {
            id: '17',
            productName: 'Поло Emporio Armani',
            category: 'polo',
            imageLinks: ['/images/clothing/polo/04/EM598EMHNFK4_10528809_1_v1_2x.jpg',
                         '/images/clothing/polo/04/EM598EMHNFK4_10528810_2_v1_2x.jpg',
                         '/images/clothing/polo/04/EM598EMHNFK4_10528811_3_v1_2x.jpg',
                         '/images/clothing/polo/04/EM598EMHNFK4_10528812_4_v1_2x.jpg'],
            price: 8500,
            sizes: ['54', '56'],
            color: ['черный'],
            material: ['Хлопок', 'Эластан'],
            season: 'мульти',
            description: 'Поло от премиум-бренда выполнено из хлопкового трикотажа. Особенности: отложной воротник, застежка на пуговицы, съемная нашивка с логотипом бренда, короткий рукав с эластичными манжетами.'

        },
        {
            id: '18',
            productName: 'Поло Polo Ralph Lauren',
            category: 'polo',
            imageLinks: ['/images/clothing/polo/05/PO006EMHTZX1_11072095_1_v1_2x.jpg',
                         '/images/clothing/polo/05/PO006EMHTZX1_11072096_2_v1_2x.jpg',
                         '/images/clothing/polo/05/PO006EMHTZX1_11072097_3_v1_2x.jpg',
                         '/images/clothing/polo/05/PO006EMHTZX1_11072098_4_v1_2x.jpg'],
            price: 14000,
            sizes: ['50'],
            color: ['синий', 'белый', 'черный'],
            material: ['Хлопок'],
            season: 'мульти',
            description: 'Поло от премиального бренда выполнено из хлопкового трикотажа с  оригинальным принтом. Модель прямого кроя. Особенности: воротник-поло, короткие рукава.'

        },
        {
            id: '19',
            productName: 'Поло Just Cavalli',
            category: 'polo',
            imageLinks: ['/images/clothing/polo/06/JU662EMHXKV0_10843552_1_v1_2x.jpg',
                         '/images/clothing/polo/06/JU662EMHXKV0_10843553_2_v1_2x.jpg',
                         '/images/clothing/polo/06/JU662EMHXKV0_10843554_3_v1_2x.jpg',
                         '/images/clothing/polo/06/JU662EMHXKV0_10843555_4_v1_2x.jpg'],
            price: 11000,
            sizes: ['48', '50', '54'],
            color: ['белый'],
            material: ['Хлопок'],
            season: 'мульти',
            description: 'Поло от премиум-бренда выполнено из хлопкового трикотажа. Модель прямого кроя. Особенности: вырез-поло, планка с застежкой на пуговицы.'

        },
        {
            id: '20',
            productName: 'Поло Cortigiani',
            category: 'polo',
            imageLinks: ['/images/clothing/polo/07/CO068EMHEVT2_10914140_1_v1_2x.jpg',
                         '/images/clothing/polo/07/CO068EMHEVT2_10914141_2_v1_2x.jpg',
                         '/images/clothing/polo/07/CO068EMHEVT2_10914142_3_v1_2x.jpg',
                         '/images/clothing/polo/07/CO068EMHEVT2_10914143_4_v1_2x.jpg'],
            price: 15000,
            sizes: ['48', '50', '52', '56'],
            color: ['синий'],
            material: ['Хлопок'],
            season: 'мульти',
            description: 'Поло от премиум-бренда выполнено из хлопкового трикотажа. Модель прямого кроя. Особенности: вырез-поло, планка с застежкой на пуговицы.'

        },

        //SHIRTS
        {
            id: '21',
            productName: 'Рубашка Boss',
            category: 'shirts',
            imageLinks: ['/images/clothing/shirts/01/MP002XM0519D_8927533_1_v2_2x.jpg',
                         '/images/clothing/shirts/01/MP002XM0519D_8943114_2_v1_2x.jpg',
                         '/images/clothing/shirts/01/MP002XM0519D_8943115_3_v1_2x.jpg',
                         '/images/clothing/shirts/01/MP002XM0519D_8943116_4_v1_2x.jpg'],
            price: 13000,
            sizes: ['37', '38', '40', '41', '42', '43', '44', '45'],
            color: ['белый'],
            material: ['Хлопок'],
            season: 'мульти',
            description: 'Рубашка от премиум-бренда выполнена из натурального хлопка. Модель приталенного силуэта. Особенности: застежка пуговицы, отрезная кокетка по спинке.'

        },
        {
            id: '22',
            productName: 'Рубашка Boss Lukas_53',
            category: 'shirts',
            imageLinks: ['/images/clothing/shirts/02/MP002XM1RN05_10779362_2_v1_2x.jpg',
                         '/images/clothing/shirts/02/MP002XM1RN05_10779363_3_v1_2x.jpg',
                         '/images/clothing/shirts/02/MP002XM1RN05_10779364_4_v1_2x.jpg',
                         '/images/clothing/shirts/02/MP002XM1RN05_10779365_5_v1_2x.jpg'],
            price: 12000,
            sizes: ['52', '54'],
            color: ['белый'],
            material: ['Лен'],
            season: 'мульти',
            description: 'Рубашка от премиального бренда выполнена из натурального льна. Особенности: прямой крой, застежка на пуговицы, отложной воротник, длинные рукава с манжетами на пуговицах.'

        },
        {
            id: '23',
            productName: 'Рубашка Millennials',
            category: 'shirts',
            imageLinks: ['/images/clothing/shirts/03/MP002XM0WJ5N_10742165_2_v1.jpg',
                         '/images/clothing/shirts/03/MP002XM0WJ5N_10742167_3_v1.jpg',
                         '/images/clothing/shirts/03/MP002XM0WJ5N_10742168_5_v1.jpg',
                         '/images/clothing/shirts/03/MP002XM0WJ5N_10742169_6_v1.jpg'],
            price: 11800,
            sizes: ['46', '48', '50', '52', '54'],
            color: ['черный'],
            material: ['Хлопок'],
            season: 'мульти',


        },
        {
            id: '24',
            productName: 'Рубашка Polo Ralph Lauren',
            category: 'shirts',
            imageLinks: ['/images/clothing/shirts/04/MP002XM20XAL_11076886_1_v1_2x.jpg',
                         '/images/clothing/shirts/04/MP002XM20XAL_11076887_2_v1_2x.jpg',
                         '/images/clothing/shirts/04/MP002XM20XAL_11076888_3_v1_2x.jpg',
                         '/images/clothing/shirts/04/MP002XM20XAL_11076889_4_v1_2x.jpg'],
            price: 11900,
            sizes: ['48'],
            color: ['голубой'],
            material: ['Хлопок'],
            season: 'мульти',
            description: 'Рубашка выполнена из льняного текстиля. Особенности: приталенный крой, застежка - пуговицы, воротник на пуговицах, вышитая эмблема бренда.'

        },
        {
            id: '25',
            productName: 'Рубашка Polo Ralph Lauren',
            category: 'shirts',
            imageLinks: ['/images/clothing/shirts/05/MP002XM052HM_11331496_1_v1_2x.jpg',
                         '/images/clothing/shirts/05/MP002XM052HM_11331497_2_v1_2x.jpg',
                         '/images/clothing/shirts/05/MP002XM052HM_11331498_3_v1_2x.jpg',
                         '/images/clothing/shirts/05/MP002XM052HM_11331499_4_v1_2x.jpg'],
            price: 12700,
            sizes: ['46', '48', '50', '52'],
            color: ['серый'],
            material: ['Лен'],
            season: 'мульти',
            description: 'Рубашка от премиального бренда выполнена из натурального льна. Особенности: прямой крой, застежка на пуговицы, отложной воротник, длинные рукава с манжетами на пуговицах.'

        },
        {
            id: '26',
            productName: 'Рубашка Boss',
            category: 'shirts',
            imageLinks: ['/images/clothing/shirts/06/MP002XM20XAT_11076899_1_v1_2x.jpg',
                         '/images/clothing/shirts/06/MP002XM20XAT_11076900_2_v1_2x.jpg',
                         '/images/clothing/shirts/06/MP002XM20XAT_11076901_3_v1_2x.jpg',
                         '/images/clothing/shirts/06/MP002XM20XAT_11076902_4_v1_2x.jpg'],
            price: 11000,
            sizes: ['45', '50', '52'],
            color: ['белый'],
            material: ['Лен'],
            season: 'мульти',
            description: 'Рубашка выполнена из льняного текстиля. Особенности: лаконичный дизайн, контрастная вышивка логотипа бренда, прямой силуэт, воротник баттен-даун, застежка на пуговицах.'

        },

        //SUITS

        {
            id: '27',
            productName: 'Костюм классический Brian Dales',
            category: 'suits',
            imageLinks: ['/images/clothing/suits/01/BR049EMHVCB7_10544249_1_v1_2x.jpg',
                         '/images/clothing/suits/01/BR049EMHVCB7_10544250_2_v1_2x.jpg',
                         '/images/clothing/suits/01/BR049EMHVCB7_10544251_3_v1_2x.jpg',
                         '/images/clothing/suits/01/BR049EMHVCB7_10544252_4_v1_2x.jpg'],
            price: 34000,
            sizes: ['50', '52', '54','56'],
            color: ['синий'],
            material: ['Шерсть'],
            season: 'мульти',
            description: 'Костюм от премиум-бренда выполнен из текстиля и состоит из пиджака и брюк. Особенности пиджака: застежка на пуговицах, два внутренних кармана, приталенный крой, тонкая жаккардовая подкладка. Особенности брюк: шлевки для ремня, застежка на молнии и крючке, стрелки, четыре кармана.'

        },
        {
            id: '28',
            productName: 'Костюм классический Boss Novan6/Ben2',
            category: 'suits',
            imageLinks: ['/images/clothing/suits/02/MP002XM1K3TP_9423668_1_v1.jpg',
                         '/images/clothing/suits/02/MP002XM1K3TP_9423669_2_v1.jpg',
                         '/images/clothing/suits/02/MP002XM1K3TP_9423670_3_v1.jpg',
                         '/images/clothing/suits/02/MP002XM1K3TP_9423671_4_v1.jpg'],
            price: 49755,
            sizes: ['48', '50', '52','54', '58'],
            color: ['серый'],
            material: ['Шерсть'],
            season: 'демисезон',
            description: 'Классический костюм-двойка выполнен из натуральной шерсти с саржевым переплетением и ненавязчивым микрорисунком. Гладкая подкладка обеспечивает дополнительный комфорт. Особенности пиджака: приталенный крой, однобортная застежка на двух пуговицах, три наружных кармана, 2 шлицы сзади. Особенности: зауженный крой, застежка на молнии и крючках, 2 боковых кармана и 2 прорезных кармана сзади, шлевки на поясе для ремня.'

        },
        {
            id: '29',
            productName: 'Костюм классический Boss',
            category: 'suits',
            imageLinks: ['/images/clothing/suits/03/MP002XM1RMZ8_10488363_1_v3_2x.jpg',
                         '/images/clothing/suits/03/MP002XM1RMZ8_10488364_2_v3_2x.jpg',
                         '/images/clothing/suits/03/MP002XM1RMZ8_10488365_3_v3_2x.jpg',
                         '/images/clothing/suits/03/MP002XM1RMZ8_10488366_4_v3_2x.jpg'],
            price: 39700,
            sizes: ['46', '54', '58'],
            color: ['серый'],
            material: ['Вискоза '],
            season: 'мульти',
            description: 'Костюм выполнен из плотного текстиля. Особенности пиджака: полуприталенный крой, застежка на пуговицах, воротник с лацканами, один нагрудный карман, прорезные боковые карманы с лацканами, атласная подкладка. Особенности брюк: зауженный книзу крой, застежка на молнию и пуговицу, шлевки для ремня, два боковых кармана, два прорезных кармана с застежкой на пуговицу сзади.'

        },
        {
            id: '30',
            productName: 'Костюм классический Pal Zileri',
            category: 'suits',
            imageLinks: ['/images/clothing/suits/04/PA413EMITYE1_11083454_1_v1_2x.jpg',
                         '/images/clothing/suits/04/PA413EMITYE1_11083455_2_v1_2x.jpg',
                         '/images/clothing/suits/04/PA413EMITYE1_11083456_3_v1_2x.jpg',
                         '/images/clothing/suits/04/PA413EMITYE1_11083457_4_v1_2x.jpg'],
            price: 53100,
            sizes: ['50', '52'],
            color: ['синий'],
            material: ['Шерсть'],
            season: 'мульти',
            description: 'Костюм от премиум-бренда выполнен из шерстяного текстиля и состоит из пиджака и брюк. Особенности пиджака: застежка на пуговицах, два внутренних кармана, приталенный '

        },
        {
            id: '31',
            productName: 'Костюм классический Emporio Armani',
            category: 'suits',
            imageLinks: ['/images/clothing/suits/05/EM598EMHNEU2_10219218_1_v1_2x.jpg',
                         '/images/clothing/suits/05/EM598EMHNEU2_10219219_2_v1_2x.jpg',
                         '/images/clothing/suits/05/EM598EMHNEU2_10219220_3_v1_2x.jpg',
                         '/images/clothing/suits/05/EM598EMHNEU2_10219221_4_v1_2x.jpg'],
            price: 45600,
            sizes: ['50'],
            color: ['синий'],
            material: ['Шерсть'],
            season: 'мульти',
            description: 'Костюм премиального бренда выполнен из шерстяного текстиля. Особенности: пиджак с застежкой на пуговицах, текстильной подкладкой, длинными рукавами, воротником с лацканами, двумя боковыми карманами, тремя внутренними карманами, брюки зауженного кроя с застежкой на молнии, четырьмя внешними карманами.'

        },
        {
            id: '32',
            productName: 'Костюм классический Boss',
            category: 'suits',
            imageLinks: ['/images/clothing/suits/06/MP002XM12CCH_11406373_1_v1_2x.jpg',
                         '/images/clothing/suits/06/MP002XM12CCH_11406374_2_v1_2x.jpg',
                         '/images/clothing/suits/06/MP002XM12CCH_11406375_3_v1_2x.jpg',
                         '/images/clothing/suits/06/MP002XM12CCH_11406376_4_v1_2x.jpg'],
            price: 34000,
            sizes: ['50', '52'],
            color: ['синий'],
            material: ['Шерсть'],
            season: 'мульти',
            description: 'Костюм состоит из пиджака и брюк, выполненных из клетчатого шерстяного текстиля. Особенности: пиджак приталенного кроя, застежка на пуговицы, три кармана. Брюки зауженного кроя, застежка на молнию и крючок, боковые и задние карманы.'

        },
        {
            id: '33',
            productName: 'Костюм классический Boss Huge6/Genius5',
            category: 'suits',
            imageLinks: ['/images/clothing/suits/07/MP002XM1RMYQ_10829778_1_v2_2x.jpg',
                         '/images/clothing/suits/07/MP002XM1RMYQ_10829779_2_v2_2x.jpg',
                         '/images/clothing/suits/07/MP002XM1RMYQ_10829780_3_v2_2x.jpg',
                         '/images/clothing/suits/07/MP002XM1RMYQ_10829781_4_v2_2x.jpg'],
            price: 25500,
            sizes: ['48', '50'],
            color: ['черный'],
            material: ['Шерсть'],
            season: 'мульти',
            description: 'Классический костюм состоит из пиджака и брюк. Изделия выполнены из тонкого шерстяного текстиля. Особенности пиджака: приталенный силуэт, застежка на пуговицах, 3 наружных кармана и 3 кармана внутренних, шлица сзади, шелковистая подкладка. Особенности брюк: застежка на молнии и пуговице, пояс со шлевками.'

        },

        //TROUSERS

        {
            id: '34',
            productName: 'Брюки Mango Man Paulo',
            category: 'trousers',
            imageLinks: ['/images/clothing/trousers/01/HE002EMIEGC7_10249069_1_v1.jpg',
                         '/images/clothing/trousers/01/HE002EMIEGC7_10249070_2_v1.jpg',
                         '/images/clothing/trousers/01/HE002EMIEGC7_10249071_3_v1.jpg'],
            price: 4200,
            sizes: ['42', '44', '46', '48', '50'],
            color: ['черный'],
            material: ['Полиэстер', 'Вискоза', 'Эластан'],
            season: 'мульти',
        },
        {
            id: '35',
            productName: 'Брюки Stenser',
            category: 'trousers',
            imageLinks: ['/images/clothing/trousers/02/MP002XM0LZCC_5765099_1_v2.jpg',
                         '/images/clothing/trousers/02/MP002XM0LZCC_5765102_2_v2.jpg',
                         '/images/clothing/trousers/02/MP002XM0LZCC_5765105_3_v2.jpg'],
            price: 4000,
            sizes: ['48', '50', '52', '54', '58'],
            color: ['черный'],
            material: ['Шерсть', 'Вискоза', 'Ацетат', 'Лайкра'],
            season: 'демисезон',
            description: 'Ткань верха - средней плотности. Пояс с составным корсажем средней жёсткости, собран по "бесшовной" технологии. Линия посадки пояса брюк немного ниже естественной линии талии. Пояс застегивается на металлический крючок, выступ пояса застегивается на пуговицу. Карманы, шлёвки усилены закрепками.'
        },
        {
            id: '36',
            productName: 'Брюки Stenser',
            category: 'trousers',
            imageLinks: ['/images/clothing/trousers/03/MP002XM1Q0LA_10673262_1_v1_2x.jpg',
                         '/images/clothing/trousers/03/MP002XM1Q0LA_10673263_2_v1_2x.jpg',
                         '/images/clothing/trousers/03/MP002XM1Q0LA_10673264_3_v1_2x.jpg'],
            price: 3700,
            sizes: ['46', '48', '56'],
            color: ['синий'],
            material: ['Полиэстер', 'Вискоза'],
            season: 'мульти',
        },
        {
            id: '37',
            productName: 'Брюки Boss Johnstons',
            category: 'trousers',
            imageLinks: ['/images/clothing/trousers/04/BU014EMILNM5_10394757_1_v1.jpg',
                         '/images/clothing/trousers/04/BU014EMILNM5_10394758_2_v1.jpg'],
            price: 3100,
            sizes: ['30', '32', '34', '36', '38'],
            color: ['синий'],
            material: ['Полиэстер', 'Вискоза', 'Эластан'],
            season: 'мульти',
        },
        {
            id: '38',
            productName: 'Брюки Mason Grace',
            category: 'trousers',
            imageLinks: ['/images/clothing/trousers/05/MP002XM20MA4_10140588_1_v1_2x.jpg',
                         '/images/clothing/trousers/05/MP002XM20MA4_10140589_2_v1_2x.jpg',
                         '/images/clothing/trousers/05/MP002XM20MA4_10140590_3_v1_2x.jpg'],
            price: 3200,
            sizes: ['46', '50', '54'],
            color: ['синий'],
            material: ['Шерсть', 'Вискоза', 'Эластан'],
            season: 'мульти',
        },
        {
            id: '39',
            productName: 'Брюки Bazioni',
            category: 'trousers',
            imageLinks: ['/images/clothing/trousers/06/MP002XM1PZBB_9762201_1_v1_2x.jpg',
                         '/images/clothing/trousers/06/MP002XM1PZBB_9762202_2_v1_2x.jpg',
                         '/images/clothing/trousers/06/MP002XM1PZBB_9762203_3_v1_2x.jpg'],
            price: 8700,
            sizes: ['46', '48', '50', '52', '54', '56'],
            color: ['синий'],
            material: ['Шерсть', 'Лайкра'],
            season: 'мульти',
        },
        {
            id: '40',
            productName: 'Брюки DeFacto',
            category: 'trousers',
            imageLinks: ['/images/clothing/trousers/07/MP002XM24U10_11300431_1_v1_2x.jpg',
                         '/images/clothing/trousers/07/MP002XM24U10_11300432_2_v1_2x.jpg',
                         '/images/clothing/trousers/07/MP002XM24U10_11300433_3_v1_2x.jpg'],
            price: 2100,
            sizes: ['28', '30', '32', '34', '36'],
            color: ['серый'],
            material: ['Полиэстер', 'Вискоза', 'Эластан'],
            season: 'мульти',
        },

        //T-SHIRTS

        {
            id: '41',
            productName: 'Футболка Marcelo Burlon County of Milan',
            category: 't-shirts',
            imageLinks: ['/images/clothing/t-shirts/01/MA203EMJMWM7_11451514_1_v1_2x.jpg',
                         '/images/clothing/t-shirts/01/MA203EMJMWM7_11451515_2_v1_2x.jpg',
                         '/images/clothing/t-shirts/01/MA203EMJMWM7_11451516_3_v1_2x.jpg',
                         '/images/clothing/t-shirts/01/MA203EMJMWM7_11451517_4_v1_2x.jpg'],
            price: 20900,
            sizes: ['46', '48', '50', '52', '54'],
            color: ['черный'],
            material: ['Хлопок'],
            season: 'мульти',
            description: 'Футболка выполнена из хлопкового материала. Модель прямого кроя. Особенности: круглый вырез, короткие рукава.'
        },

        {
            id: '42',
            productName: 'Футболка Versace Jeans Couture',
            category: 't-shirts',
            imageLinks: ['/images/clothing/t-shirts/02/VE035EMHYTE3_11020059_1_v1_2x.jpg',
                         '/images/clothing/t-shirts/02/VE035EMHYTE3_11020060_2_v1_2x.jpg',
                         '/images/clothing/t-shirts/02/VE035EMHYTE3_11020061_3_v1_2x.jpg',
                         '/images/clothing/t-shirts/02/VE035EMHYTE3_11020062_4_v1_2x.jpg'],
            price: 13700,
            sizes: ['46', '48', '50'],
            color: ['черный'],
            material: ['Хлопок', 'Эластан'],
            season: 'мульти',
            description: 'Футболка выполнена из хлопкового трикотажа. Модель прямого кроя. Особенности: круглый вырез, резинка в мелкий рубчик на вырезе ворота, фантазийный принт.'
        },
        {
            id: '43',
            productName: 'Футболка Marni',
            category: 't-shirts',
            imageLinks: ['/images/clothing/t-shirts/03/MA177EMHWYF0_10879947_1_v1_2x.jpg',
                         '/images/clothing/t-shirts/03/MA177EMHWYF0_10879948_2_v1_2x.jpg',
                         '/images/clothing/t-shirts/03/MA177EMHWYF0_10879949_3_v1_2x.jpg',
                         '/images/clothing/t-shirts/03/MA177EMHWYF0_10879950_4_v1_2x.jpg'],
            price: 12300,
            sizes: ['50', '52'],
            color: ['оранжевый'],
            material: ['Хлопок'],
            season: 'мульти',
            description: 'Футболка выполнена из плотного хлопкового трикотажа. Модель свободного силуэта. Особенности: комбинированный дизайн, круглый вырез горловины, короткий рукав.'
        },
        {
            id: '44',
            productName: 'Футболка Automobili Lamborghini',
            category: 't-shirts',
            imageLinks: ['/images/clothing/t-shirts/04/AU007EMJEXE7_11018330_1_v1_2x.jpg',
                         '/images/clothing/t-shirts/04/AU007EMJEXE7_11018331_2_v1_2x.jpg',
                         '/images/clothing/t-shirts/04/AU007EMJEXE7_11018332_3_v1_2x.jpg',
                         '/images/clothing/t-shirts/04/AU007EMJEXE7_11018333_4_v1_2x.jpg'],
            price: 10200,
            sizes: ['48', '52'],
            color: ['белый', 'оранжевый', 'черный', 'серый'],
            material: ['Хлопок'],
            season: 'мульти',
            description: 'Футболка выполнена из хлопкового трикотажа. Модель прямого кроя. Особенности: круглый вырез, резинка в мелкий рубчик на вырезе ворота, термоаппликация с логотипом бренда на груди.'
        },
        {
            id: '45',
            productName: 'Футболка Just Cavalli',
            category: 't-shirts',
            imageLinks: ['/images/clothing/t-shirts/05/JU662EMHJBK8_10260629_1_v1_2x.jpg',
                         '/images/clothing/t-shirts/05/JU662EMHJBK8_10260630_2_v1_2x.jpg',
                         '/images/clothing/t-shirts/05/JU662EMHJBK8_10260631_3_v1_2x.jpg',
                         '/images/clothing/t-shirts/05/JU662EMHJBK8_10260632_4_v1_2x.jpg'],
            price: 8800,
            sizes: ['48'],
            color: ['белый'],
            material: ['Хлопок'],
            season: 'мульти',
            description: 'Футболка выполнена из натурального хлопка. Особенности: прямой крой, принт с названием бренда.'
        },
        {
            id: '46',
            productName: 'Футболка Moschino Couture',
            category: 't-shirts',
            imageLinks: ['/images/clothing/t-shirts/06/MO101EMICEH0_11268975_1_v1_2x.jpg',
                         '/images/clothing/t-shirts/06/MO101EMICEH0_11268976_2_v1_2x.jpg',
                         '/images/clothing/t-shirts/06/MO101EMICEH0_11268977_3_v1_2x.jpg',
                         '/images/clothing/t-shirts/06/MO101EMICEH0_11268978_4_v1_2x.jpg'],
            price: 17700,
            sizes: ['46', '48', '50'],
            color: ['серый'],
            material: ['Хлопок'],
            season: 'мульти',
            description: 'Футболка от премиального бренда выполнена из хлопкового трикотажа. Особенности: круглый вырез горловины, короткие рукава.'
        },
        {
            id: '47',
            productName: 'Футболка Plein Sport',
            category: 't-shirts',
            imageLinks: ['/images/clothing/t-shirts/07/PL007EMJQHA2_11448140_1_v1_2x.jpg',
                         '/images/clothing/t-shirts/07/PL007EMJQHA2_11448141_2_v1_2x.jpg',
                         '/images/clothing/t-shirts/07/PL007EMJQHA2_11448142_3_v1_2x.jpg',
                         '/images/clothing/t-shirts/07/PL007EMJQHA2_11448143_4_v1_2x.jpg'],
            price: 15600,
            sizes: ['48', '50','54'],
            color: ['черный'],
            material: ['Хлопок', 'Эластан'],
            season: 'мульти',
            description: 'Футболка от премиального бренда выполнена из хлопкового трикотажа. Особенности: круглый вырез горловины, короткие рукава, термоаппликация с логотипом бренда.'
        },

        //BELTS

        {
            id: '48',
            productName: 'Ремень Hugo Elvio-U',
            category: 'belts',
            imageLinks: ['/images/accessories/belts/01/MP002XM1ZJTV_10791599_1_v1.jpg',
                         '/images/accessories/belts/01/MP002XM1ZJTV_10791600_2_v1.jpg',],
            price: 6000,
            sizes: ['80', '85','90', '95', '100'],
            color: ['черный'],
            material: ['Коровья кожа'],
            season: 'мульти',
            description: 'Ремень выполнен из коровьей кожи. Особенности: гладкая фактура, классическая пряжка, лаконичный дизайн.'
        },
        {
            id: '49',
            productName: 'Ремень Tommy Hilfiger',
            category: 'belts',
            imageLinks: ['/images/accessories/belts/02/TO263DMOLT26_4122251_1_v3.jpg',
                         '/images/accessories/belts/02/TO263DMOLT26_4122252_2_v3.jpg',],
            price: 3200,
            sizes: ['90', '100','105'],
            color: ['коричневый'],
            material: ['Натуральная кожа'],
            season: 'мульти',
        },
        {
            id: '50',
            productName: 'Ремень Alexander Tsiselsky',
            category: 'belts',
            imageLinks: ['/images/accessories/belts/03/MP002XM1Q0Z5_10436540_1_v1.jpg',
                         '/images/accessories/belts/03/MP002XM1Q0Z5_10436541_2_v1.jpg',],
            price: 4600,
            color: ['коричневый'],
            material: ['Натуральная кожа'],
            season: 'мульти',

        },

        //GLOVES

        {
            id: '51',
            productName: 'Перчатки Celio',
            category: 'gloves',
            imageLinks: ['/images/accessories/gloves/01/CE007DMFKEG9_10223901_1_v1.jpg',
                         '/images/accessories/gloves/01/CE007DMFKEG9_10223902_2_v1.jpg',],
            price: 1200,
            sizes: ['80', '85','90', '95', '100'],
            color: ['коричневый'],
            material: ['Натуральная кожа'],
            season: 'демисезон',

        },
        {
            id: '52',
            productName: 'Перчатки Esmee',
            category: 'gloves',
            imageLinks: ['/images/accessories/gloves/02/MP002XM1Q0TZ_10371613_1_v1.jpg',
                         '/images/accessories/gloves/02/MP002XM1Q0TZ_10371614_2_v1.jpg',],
            price: 3800,
            color: ['черный'],
            material: ['Кожа ягненка'],
            season: 'демисезон',

        },
        {
            id: '53',
            productName: 'Перчатки Dr.Koffer',
            category: 'gloves',
            imageLinks: ['/images/accessories/gloves/03/MP002XM23WUQ_7513497_1_v1.jpg',
                         '/images/accessories/gloves/03/MP002XM23WUQ_7513498_2_v1.jpg',],
            price: 7000,
            color: ['коричневый'],
            material: ['Натуральная кожа'],
            season: 'демисезон',

        },

        //HATS

        {
            id: '54',
            productName: 'Шляпа Stetson',
            category: 'hats',
            imageLinks: ['/images/accessories/hats/01/MP002XU0365C_11317963_1_v3.jpg',
                         '/images/accessories/hats/01/MP002XU0365C_11317964_2_v3.jpg',],
            price: 15700,
            sizes: ['59'],
            color: ['белый'],
            material: ['Солома '],
            season: 'лето',

        },
        {
            id: '55',
            productName: 'Бейсболка Baldinini',
            category: 'hats',
            imageLinks: ['/images/accessories/hats/02/BA097CMJECC0_10910508_1_v1.jpg',
                         '/images/accessories/hats/02/BA097CMJECC0_10910509_2_v1.jpg',],
            price: 7800,
            sizes: ['56', '58', '60'],
            color: ['синий'],
            material: ['Хлопок'],
            season: 'мульти',
            description: 'Бейсболка от премиум-бренда выполнен из хлопка. Особенности: жесткий козырек, минималистичный дизайн, металлический регулятор длинны.'

        },
        {
            id: '56',
            productName: 'Кепка Stetson',
            category: 'hats',
            imageLinks: ['/images/accessories/hats/03/MP002XU02HQV_8871659_1_v12.jpg',
                         '/images/accessories/hats/03/MP002XU02HQV_8871661_2_v12.jpg',],
            price: 6000,
            sizes: ['57','59'],
            color: ['синий'],
            material: ['Хлопок'],
            season: 'демисезон',

        },

        //TIES

        {
            id: '57',
            productName: 'Галстук Boss',
            category: 'ties',
            imageLinks: ['/images/accessories/ties/01/MP002XM1K7UM_10936220_2_v2.jpg',
                         '/images/accessories/ties/01/MP002XM1K7UM_10936221_1_v2.jpg',],
            price: 4000,
            color: ['синий'],
            material: ['Полиэстер'],
            season: 'мульти',

        },
        {
            id: '58',
            productName: 'Галстук Ir.Lush',
            category: 'ties',
            imageLinks: ['/images/accessories/ties/02/MP002XM20UIH_11165669_1_v1.jpg',
                         '/images/accessories/ties/02/MP002XM20UIH_11165670_2_v1.jpg',],
            price: 1700,
            color: ['синий'],
            material: ['Микрофибра'],
            season: 'мульти',

        },
        {
            id: '59',
            productName: 'Галстук Henderson',
            category: 'ties',
            imageLinks: ['/images/accessories/ties/03/MP002XM24S6Q_11453520_1_v1.jpg',
                         '/images/accessories/ties/03/MP002XM24S6Q_11453521_2_v1.jpg',],
            price: 2300,
            color: ['синий'],
            material: ['Натуральный шелк'],
            season: 'мульти',

        },

        //WALLETS

        {
            id: '60',
            productName: "Кошелек Levi's®",
            category: 'wallets',
            imageLinks: ['/images/accessories/wallets/01/LE306BMHPTU8_10734083_1_v1.jpg',
                         '/images/accessories/wallets/01/LE306BMHPTU8_10734084_2_v1.jpg',],
            price: 2600,
            color: ['черный'],
            material: ['Натуральная кожа'],
            season: 'мульти',

        },
        {
            id: '61',
            productName: "Визитница Dimanche",
            category: 'wallets',
            imageLinks: ['/images/accessories/wallets/02/DI042DMEFBQ1_8050005_1_v1.jpg',
                         '/images/accessories/wallets/02/DI042DMEFBQ1_8050006_2_v1.jpg',],
            price: 800,
            color: ['коричневый'],
            material: ['Натуральная кожа'],
            season: 'мульти',
            description: 'Визитница выполнена из натуральной кожи. Детали: 1 отделение на молнии, 6 слотов для пластиковых карт.'

        },
        {
            id: '62',
            productName: "Кошелек Cerruti 1881",
            category: 'wallets',
            imageLinks: ['/images/accessories/wallets/03/CE899BMILCY5_10649042_1_v1.jpg',
                         '/images/accessories/wallets/03/CE899BMILCY5_10649043_2_v1.jpg',],
            price: 11000,
            color: ['черный'],
            material: ['Натуральная кожа'],
            season: 'мульти',
            description: 'Кошелек от премиум-бренда выполнен из натуральной кожи. Особенности: застежка на молнии, три отделения для купюр, два кармана, одно отделение с застежкой на молнии для монет, восемь слотов для пластиковых карт.'

        },

        //FORMAL-SHOES
        {
            id: '63',
            productName: "Туфли Baldinini",
            category: 'formal-shoes',
            imageLinks: ['/images/shoes/formal-shoes/01/BA097AMIQJJ9_11071247_1_v1.jpg',
                         '/images/shoes/formal-shoes/01/BA097AMIQJJ9_11071248_2_v1.jpg',
                         '/images/shoes/formal-shoes/01/BA097AMIQJJ9_11071249_3_v1.jpg',
                         '/images/shoes/formal-shoes/01/BA097AMIQJJ9_11071250_4_v1.jpg',],
            price: 33600,
            color: ['синий'],
            sizes: ['40', '43', '44','45'],
            material: ['Натуральная кожа'],
            season: 'мульти',
            description: 'Туфли от премиум-бренда полностью выполнены из натуральной кожи. Особенности: гладкая подошва.'

        },
        {
            id: '64',
            productName: "Лоферы F.lli Rennella",
            category: 'formal-shoes',
            imageLinks: ['/images/shoes/formal-shoes/02/FL025AMJKHZ8_11422060_1_v1.jpg',
                         '/images/shoes/formal-shoes/02/FL025AMJKHZ8_11422061_2_v1.jpg',
                         '/images/shoes/formal-shoes/02/FL025AMJKHZ8_11422062_3_v1.jpg',
                         '/images/shoes/formal-shoes/02/FL025AMJKHZ8_11422063_4_v1.jpg',],
            price: 10900,
            color: ['синий'],
            sizes: ['39','40', '41', '42', '43', '44'],
            material: ['Натуральная кожа'],
            season: 'мульти',


        },
        {
            id: '65',
            productName: "Лоферы Rossini Roberto",
            category: 'formal-shoes',
            imageLinks: ['/images/shoes/formal-shoes/03/MP002XM24WCU_11398797_1_v1.jpg',
                         '/images/shoes/formal-shoes/03/MP002XM24WCU_11398798_2_v1.jpg',
                         '/images/shoes/formal-shoes/03/MP002XM24WCU_11398799_3_v1.jpg',
                         '/images/shoes/formal-shoes/03/MP002XM24WCU_11398800_4_v1.jpg',],
            price: 6400,
            color: ['черный'],
            sizes: ['39', '40', '41','42', '44'],
            material: ['Натуральная кожа'],
            season: 'лето',


        },
        {
            id: '66',
            productName: "Туфли El'Rosso",
            category: 'formal-shoes',
            imageLinks: ['/images/shoes/formal-shoes/04/EL032AMJCLM0_10903372_1_v1.jpg',
                         '/images/shoes/formal-shoes/04/EL032AMJCLM0_10903373_2_v1.jpg',
                         '/images/shoes/formal-shoes/04/EL032AMJCLM0_10903374_3_v1.jpg',
                         '/images/shoes/formal-shoes/04/EL032AMJCLM0_10903375_4_v1.jpg',],
            price: 18000,
            color: ['черный'],
            sizes: ['39', '40', '41', '42','44'],
            material: ['Натуральная кожа'],
            season: 'мульти',


        },
        {
            id: '67',
            productName: "Лоферы Vera Victoria Vito",
            category: 'formal-shoes',
            imageLinks: ['/images/shoes/formal-shoes/05/VE176AMYQK59_5645357_1_v2.jpg',
                         '/images/shoes/formal-shoes/05/VE176AMYQK59_5645358_2_v2.jpg',
                         '/images/shoes/formal-shoes/05/VE176AMYQK59_5645359_3_v2.jpg',
                         '/images/shoes/formal-shoes/05/VE176AMYQK59_5645360_4_v2.jpg',],
            price: 7700,
            color: ['черный'],
            sizes: ['39', '40', '41','44'],
            material: ['Натуральная кожа'],
            season: 'мульти',

        },
        {
            id: '68',
            productName: "Лоферы Roberto Cavalli",
            category: 'formal-shoes',
            imageLinks: ['/images/shoes/formal-shoes/06/RO352AMIKPU7_10502229_1_v1.jpg',
                         '/images/shoes/formal-shoes/06/RO352AMIKPU7_10502230_2_v1.jpg',
                         '/images/shoes/formal-shoes/06/RO352AMIKPU7_10502231_3_v1.jpg',
                         '/images/shoes/formal-shoes/06/RO352AMIKPU7_10502232_4_v1.jpg',],
            price: 32000,
            color: ['черный'],
            sizes: ['42'],
            material: ['Натуральная кожа'],
            season: 'мульти',
            description: 'Лоферы полностью выполнены из натуральной кожи. Особенности: серебристый логотип бренда, небольшой каблучок, подошва с рельефной поверхностью.'

        },
        {
            id: '69',
            productName: "Туфли F.lli Rennella",
            category: 'formal-shoes',
            imageLinks: ['/images/shoes/formal-shoes/07/FL025AMJKID2_11422709_1_v1.jpg',
                         '/images/shoes/formal-shoes/07/FL025AMJKID2_11422710_2_v1.jpg',
                         '/images/shoes/formal-shoes/07/FL025AMJKID2_11422711_3_v1.jpg',
                         '/images/shoes/formal-shoes/07/FL025AMJKID2_11422712_4_v1.jpg',],
            price: 12000,
            color: ['коричневый'],
            sizes: ['39', '40', '41','42', '43', '44'],
            material: ['Натуральная кожа'],
            season: 'мульти',


        },

        //GUMSHOES

        {
            id: '70',
            productName: "Кеды Roberto Cavalli",
            category: 'gumshoes',
            imageLinks: ['/images/shoes/gumshoes/01/RO352AMIKPU1_11114057_1_v1.jpg',
                         '/images/shoes/gumshoes/01/RO352AMIKPU1_11114058_2_v1.jpg',
                         '/images/shoes/gumshoes/01/RO352AMIKPU1_11114059_3_v1.jpg',
                         '/images/shoes/gumshoes/01/RO352AMIKPU1_11114060_4_v1.jpg',],
            price: 31700,
            color: ['черный'],
            sizes: ['40', '43', '44'],
            material: ['Натуральная кожа'],
            season: 'демисезон',
            description: 'Кеды от премиум-бренда полностью выполнены из натуральной кожи. Особенности: высокая резиновая подошва.'

        },
        {
            id: '71',
            productName: "Кеды Roberto Botticelli",
            category: 'gumshoes',
            imageLinks: ['/images/shoes/gumshoes/02/RO233AMHWQL7_10623067_1_v1.jpg',
                         '/images/shoes/gumshoes/02/RO233AMHWQL7_10623068_2_v1.jpg',
                         '/images/shoes/gumshoes/02/RO233AMHWQL7_10623069_3_v1.jpg',
                         '/images/shoes/gumshoes/02/RO233AMHWQL7_10623070_4_v1.jpg',],
            price: 26900,
            color: ['белый'],
            sizes: ['41', '43'],
            material: ['Натуральная кожа'],
            season: 'демисезон',
            description: 'Кеды от премиум-бренда выполнены из натуральной кожи. Особенности: функциональная шнуровка, подкладка и стелька из натуральной кожи, резиновая подошва.'

        },
        {
            id: '72',
            productName: "Кеды Mister",
            category: 'gumshoes',
            imageLinks: ['/images/shoes/gumshoes/03/MI105AMIWMQ9_10914963_1_v1.jpg',
                         '/images/shoes/gumshoes/03/MI105AMIWMQ9_10914964_2_v1.jpg',
                         '/images/shoes/gumshoes/03/MI105AMIWMQ9_10914965_3_v1.jpg',
                         '/images/shoes/gumshoes/03/MI105AMIWMQ9_10914966_4_v1.jpg',],
            price: 9500,
            color: ['коричневый'],
            sizes: ['40', '41', '42', '43', '44'],
            material: ['Натуральная кожа'],
            season: 'мульти',


        },
        {
            id: '73',
            productName: "Кеды Struttura",
            category: 'gumshoes',
            imageLinks: ['/images/shoes/gumshoes/04/ST085AMJINW9_11257374_1_v1.jpg',
                         '/images/shoes/gumshoes/04/ST085AMJINW9_11257375_2_v1.jpg',
                         '/images/shoes/gumshoes/04/ST085AMJINW9_11257376_3_v1.jpg',
                         '/images/shoes/gumshoes/04/ST085AMJINW9_11257377_4_v1.jpg',],
            price: 10000,
            color: ['белый'],
            sizes: ['39', '40', '44'],
            material: ['Натуральная кожа', 'Натуральный велюр'],
            season: 'демисезон',


        },
        {
            id: '74',
            productName: "Кеды Mister",
            category: 'gumshoes',
            imageLinks: ['/images/shoes/gumshoes/05/MI105AMIWMP9_10928038_1_v1.jpg',
                         '/images/shoes/gumshoes/05/MI105AMIWMP9_10928039_2_v1.jpg',
                         '/images/shoes/gumshoes/05/MI105AMIWMP9_10928040_3_v1.jpg',
                         '/images/shoes/gumshoes/05/MI105AMIWMP9_10928041_4_v1.jpg',],
            price: 11500,
            color: ['коричневый'],
            sizes: ['39', '40', '41', '42', '43', '44', '45'],
            material: ['Хлопок'],
            season: 'демисезон',


        },
        {
            id: '75',
            productName: "Кеды Fabi",
            category: 'gumshoes',
            imageLinks: ['/images/shoes/gumshoes/06/FA075AMHXPL0_10518292_1_v1.jpg',
                         '/images/shoes/gumshoes/06/FA075AMHXPL0_10518293_2_v1.jpg',
                         '/images/shoes/gumshoes/06/FA075AMHXPL0_10518294_3_v1.jpg',
                         '/images/shoes/gumshoes/06/FA075AMHXPL0_10518295_4_v1.jpg',],
            price: 23000,
            color: ['бежевый'],
            sizes: ['42', '43'],
            material: ['Натуральная кожа'],
            season: 'мульти',
            description: 'Кеды от премиум бренда выполнены из натуральной мягкой кожи. Особенности:функциональная шнуровка. плоская подошва, перфорация по всему корпусу.'

        },
        {
            id: '76',
            productName: "Кеды Roberto Cavalli",
            category: 'gumshoes',
            imageLinks: ['/images/shoes/gumshoes/07/RO352AMIKPU2_10936930_1_v1.jpg',
                         '/images/shoes/gumshoes/07/RO352AMIKPU2_10936931_2_v1.jpg',
                         '/images/shoes/gumshoes/07/RO352AMIKPU2_10936932_3_v1.jpg',
                         '/images/shoes/gumshoes/07/RO352AMIKPU2_10936933_4_v1.jpg',],
            price: 23300,
            color: ['голубой'],
            sizes: ['41', '43', '44', '45'],
            material: ['Натуральная кожа'],
            season: 'демисезон',
            description: 'Кеды выполнены из натуральной кожи. Особенности: регулируемая застежка на шнуровку, внутренняя подкладка из натуральной кожи, перфорация, резиновая подошва.'

        },

        //MOCASSIN
        {
            id: '77',
            productName: "Мокасины Baldinini",
            category: 'moccasin',
            imageLinks: ['/images/shoes/moccasin/01/BA097AMIQJH2_10971664_1_v1.jpg',
                         '/images/shoes/moccasin/01/BA097AMIQJH2_10971665_2_v1.jpg',
                         '/images/shoes/moccasin/01/BA097AMIQJH2_10971666_3_v1.jpg',
                         '/images/shoes/moccasin/01/BA097AMIQJH2_10971667_4_v1.jpg',],
            price: 31200,
            color: ['бежевый'],
            sizes: ['44'],
            material: ['Натуральная кожа'],
            season: 'демисезон',
            description: 'Мокасины выполнены из натуральной кожи. Особенности: подкладка из кожи, перфорированный верх, гибкая подошва с протектором.'

        },
        {
            id: '78',
            productName: "Мокасины Aldo",
            category: 'moccasin',
            imageLinks: ['/images/shoes/moccasin/02/AL028AMITBN2_10665808_1_v1.jpg',
                         '/images/shoes/moccasin/02/AL028AMITBN2_10665809_2_v1.jpg',
                         '/images/shoes/moccasin/02/AL028AMITBN2_10665810_3_v1.jpg',
                         '/images/shoes/moccasin/02/AL028AMITBN2_10665811_4_v1.jpg',],
            price: 6900,
            color: ['коричневый'],
            sizes: ['39', '41', '42'],
            material: ['Натуральная замша'],
            season: 'демисезон',

        },
        {
            id: '79',
            productName: "Мокасины Wojas",
            category: 'moccasin',
            imageLinks: ['/images/shoes/moccasin/03/WO009AMIGDC7_10716676_1_v1.jpg',
                         '/images/shoes/moccasin/03/WO009AMIGDC7_10716677_2_v1.jpg',
                         '/images/shoes/moccasin/03/WO009AMIGDC7_10716678_3_v1.jpg',
                         '/images/shoes/moccasin/03/WO009AMIGDC7_10716679_4_v1.jpg',],
            price: 6300,
            color: ['синий'],
            sizes: ['39', '40', '41', '42', '43', '44'],
            material: ['Натуральный нубук'],
            season: 'демисезон',

        },
        {
            id: '80',
            productName: "Мокасины Salamander",
            category: 'moccasin',
            imageLinks: ['/images/shoes/moccasin/04/SA815AMAFXC4_6224612_1_v2.jpg',
                         '/images/shoes/moccasin/04/SA815AMAFXC4_6224613_2_v2.jpg',
                         '/images/shoes/moccasin/04/SA815AMAFXC4_6224614_3_v2.jpg',
                         '/images/shoes/moccasin/04/SA815AMAFXC4_6224615_4_v2.jpg',],
            price: 7000,
            color: ['коричневый'],
            sizes: ['40', '42', '43', '44', '45'],
            material: ['Натуральная кожа'],
            season: 'мульти',

        },
        {
            id: '81',
            productName: "Мокасины Beppi",
            category: 'moccasin',
            imageLinks: ['/images/shoes/moccasin/05/BE099AMHNRS1_10611895_1_v1.jpg',
                         '/images/shoes/moccasin/05/BE099AMHNRS1_10611896_2_v1.jpg',
                         '/images/shoes/moccasin/05/BE099AMHNRS1_10611897_3_v1.jpg',
                         '/images/shoes/moccasin/05/BE099AMHNRS1_10611898_4_v1.jpg',],
            price: 4000,
            color: ['коричневый'],
            sizes: ['40', '41', '43', '44', '45'],
            material: ['Натуральная кожа'],
            season: 'демисезон',

        },
        {
            id: '82',
            productName: "Мокасины Storm",
            category: 'moccasin',
            imageLinks: ['/images/shoes/moccasin/06/ST891AMITQN5_10764011_1_v1.jpg',
                         '/images/shoes/moccasin/06/ST891AMITQN5_10764012_2_v1.jpg',
                         '/images/shoes/moccasin/06/ST891AMITQN5_10764013_3_v1.jpg',
                         '/images/shoes/moccasin/06/ST891AMITQN5_10764014_4_v1.jpg',],
            price: 4600,
            color: ['бежевый'],
            sizes: ['38', '39', '40'],
            material: ['Натуральная кожа'],
            season: 'демисезон',

        },
        {
            id: '83',
            productName: "Мокасины El'Rosso",
            category: 'moccasin',
            imageLinks: ['/images/shoes/moccasin/07/EL032AMJCLL5_10906352_1_v1.jpg',
                         '/images/shoes/moccasin/07/EL032AMJCLL5_10906353_2_v1.jpg',
                         '/images/shoes/moccasin/07/EL032AMJCLL5_10906354_3_v1.jpg',
                         '/images/shoes/moccasin/07/EL032AMJCLL5_10906355_4_v1.jpg',],
            price: 8300,
            color: ['синий'],
            sizes: ['39', '40', '44'],
            material: ['Натуральная кожа'],
            season: 'демисезон',

        },

        //SANDALS

        {
            id: '84',
            productName: "Сандалии Marni",
            category: 'sandals',
            imageLinks: ['/images/shoes/sandals/01/MA177AMHWRE2_10613802_1_v1.jpg',
                         '/images/shoes/sandals/01/MA177AMHWRE2_10613803_2_v1.jpg',
                         '/images/shoes/sandals/01/MA177AMHWRE2_10613804_3_v1.jpg',
                         '/images/shoes/sandals/01/MA177AMHWRE2_10613805_4_v1.jpg',],
            price: 28800,
            color: ['черный'],
            sizes: ['40'],
            material: ['Текстиль'],
            season: 'лето',

        },
        {
            id: '85',
            productName: "Сандалии Caterpillar",
            category: 'sandals',
            imageLinks: ['/images/shoes/sandals/02/CA213AUIFVG3_10876139_1_v1.jpg',
                         '/images/shoes/sandals/02/CA213AUIFVG3_10876140_2_v1.jpg',
                         '/images/shoes/sandals/02/CA213AUIFVG3_10876141_3_v1.jpg',
                         '/images/shoes/sandals/02/CA213AUIFVG3_10876142_4_v1.jpg',],
            price: 6300,
            color: ['черный', 'оранжевый', 'голубой'],
            sizes: ['39', '41', '44', '45'],
            material: ['Текстиль'],
            season: 'лето',

        },
        {
            id: '86',
            productName: "Сандалии Paolo Conte",
            category: 'sandals',
            imageLinks: ['/images/shoes/sandals/03/PA743AMJDRR2_10890787_1_v1.jpg',
                         '/images/shoes/sandals/03/PA743AMJDRR2_10890788_2_v1.jpg',
                         '/images/shoes/sandals/03/PA743AMJDRR2_10890789_3_v1.jpg',
                         '/images/shoes/sandals/03/PA743AMJDRR2_10890790_4_v1.jpg',],
            price: 4000,
            color: ['черный'],
            sizes: ['39', '41', '42'],
            material: ['Натуральная кожа'],
            season: 'лето',

        },
        {
            id: '87',
            productName: "Сандалии The North Face",
            category: 'sandals',
            imageLinks: ['/images/shoes/sandals/04/TH016AMISTA1_11339158_1_v1.jpg',
                         '/images/shoes/sandals/04/TH016AMISTA1_11339159_2_v1.jpg',
                         '/images/shoes/sandals/04/TH016AMISTA1_11339160_3_v1.jpg',
                         '/images/shoes/sandals/04/TH016AMISTA1_11339161_4_v1.jpg',],
            price: 5180,
            color: ['коричневый'],
            sizes: ['40', '41', '43', '44', '45', '46'],
            material: ['Искусственная кожа'],
            season: 'демисезон',

        },
        {
            id: '88',
            productName: "Сандалии Just Couture",
            category: 'sandals',
            imageLinks: ['/images/shoes/sandals/05/JU663AMHMAX9_10514135_1_v1.jpg',
                         '/images/shoes/sandals/05/JU663AMHMAX9_10514136_2_v1.jpg',
                         '/images/shoes/sandals/05/JU663AMHMAX9_10514137_3_v1.jpg',
                         '/images/shoes/sandals/05/JU663AMHMAX9_10514138_4_v1.jpg',],
            price: 3700,
            color: ['синий'],
            sizes: ['40', '42', '43', '44', '45'],
            material: ['Текстиль'],
            season: 'лето',

        },
        {
            id: '89',
            productName: "Сандалии Tommy Jeans",
            category: 'sandals',
            imageLinks: ['/images/shoes/sandals/06/TO052AMJKXJ7_11338371_1_v1.jpg',
                         '/images/shoes/sandals/06/TO052AMJKXJ7_11338372_2_v1.jpg',
                         '/images/shoes/sandals/06/TO052AMJKXJ7_11338373_3_v1.jpg',
                         '/images/shoes/sandals/06/TO052AMJKXJ7_11338374_4_v1.jpg',],
            price: 6500,
            color: ['черный'],
            sizes: ['40'],
            material: ['Натуральная кожа'],
            season: 'лето',

        },
        {
            id: '90',
            productName: "Сандалии MaJack Wolfskinrni",
            category: 'sandals',
            imageLinks: ['/images/shoes/sandals/07/JA021AMINKF2_10816922_1_v1.jpg',
                         '/images/shoes/sandals/07/JA021AMINKF2_10816923_2_v1.jpg',
                         '/images/shoes/sandals/07/JA021AMINKF2_10816924_3_v1.jpg',
                         '/images/shoes/sandals/07/JA021AMINKF2_10816925_4_v1.jpg',],
            price: 5000,
            color: ['коричневый'],
            sizes: ['39', '41', '42', '44', '46'],
            material: ['Искусственная кожа'],
            season: 'лето',

        },

        //SNEAKERS
        {
            id: '91',
            productName: "Кроссовки Kenzo",
            category: 'sneakers',
            imageLinks: ['/images/shoes/sneakers/01/KE228AMHDNW3_9970420_1_v1.jpg',
                         '/images/shoes/sneakers/01/KE228AMHDNW3_9970421_2_v1.jpg',
                         '/images/shoes/sneakers/01/KE228AMHDNW3_9970422_3_v1.jpg',
                         '/images/shoes/sneakers/01/KE228AMHDNW3_9970423_4_v1.jpg',],
            price: 34000,
            color: ['белый'],
            sizes: ['41'],
            material: ['Натуральная  кожа'],
            season: 'демисезон',
            description: 'Кроссовки выполнены из сетчатого текстиля и натуральной кожи. . Текстильная внутренняя отделка. Особенности: шнуровка, светоотражающие элементы, износоустойчивая подошва.'

        },
        {
            id: '92',
            productName: "Кроссовки Philippe Model Paris",
            category: 'sneakers',
            imageLinks: ['/images/shoes/sneakers/02/PH008AMJDZS2_10973289_1_v1.jpg',
                         '/images/shoes/sneakers/02/PH008AMJDZS2_10973290_2_v1.jpg',
                         '/images/shoes/sneakers/02/PH008AMJDZS2_10973291_3_v1.jpg',
                         '/images/shoes/sneakers/02/PH008AMJDZS2_10973292_4_v1.jpg',],
            price: 16800,
            color: ['белый', 'синий', 'серый'],
            sizes: ['39', '40', '41', '42', '43'],
            material: ['Натуральная  кожа', 'Натуральная замша', 'Текстиль'],
            season: 'демисезон',
            description: 'Кроссовки от премиум-бренда выполнены из натуральной кожи и текстиля. Особенности: регулирующая объем шнуровка, внутренняя отделка и стелька из натуральной кожи.'

        },
        {
            id: '93',
            productName: "Кроссовки Ash",
            category: 'sneakers',
            imageLinks: ['/images/shoes/sneakers/03/AS069AMHEGU7_10275450_1_v1.jpg',
                         '/images/shoes/sneakers/03/AS069AMHEGU7_10275451_2_v1.jpg',
                         '/images/shoes/sneakers/03/AS069AMHEGU7_10275452_3_v1.jpg',
                         '/images/shoes/sneakers/03/AS069AMHEGU7_10275453_4_v1.jpg',],
            price: 13000,
            color: ['белый'],
            sizes: ['41', '42'],
            material: ['Искусственная кожа', 'Натуральный нубук', 'Текстиль'],
            season: 'демисезон',
            description: 'Кроссовки выполнены из сетчатого текстиля, натурального нубука и искусственной кожи. Формованная стелька на основе мягкого пеноматериала обеспечивает комфорт при ходьбе. Промежуточная подошва из вспененного материала для амортизации; резиновая подошва с протектором для сцепления с поверхностью. Петелька на заднике для комфортного переобувания.'

        },
        {
            id: '94',
            productName: "Кроссовки Vic Matie",
            category: 'sneakers',
            imageLinks: ['/images/shoes/sneakers/04/VI030AMIFZM4_10783289_1_v2.jpg',
                         '/images/shoes/sneakers/04/VI030AMIFZM4_10783290_2_v2.jpg',
                         '/images/shoes/sneakers/04/VI030AMIFZM4_10783291_3_v2.jpg',
                         '/images/shoes/sneakers/04/VI030AMIFZM4_10783292_4_v2.jpg',],
            price: 21000,
            color: ['белый'],
            sizes: ['39', '41', '42', '44', '46'],
            material: ['Натуральная  кожа', 'Текстиль'],
            season: 'демисезон',
            description: 'Кроссовки от премиального бренда выполнены из сетчатого текстиля и натуральной кожи. Особенности: регулируемая застежка на шнуровку, внутренняя подкладка из текстиля, стелька из натуральной кожи, резиновая подошва.'

        },
        {
            id: '95',
            productName: "Кроссовки Adidas TERREX FREE HIKER PARLEY",
            category: 'sneakers',
            imageLinks: ['/images/shoes/sneakers/05/AD002AMHLNP9_10595203_1_v1.jpg',
                         '/images/shoes/sneakers/05/AD002AMHLNP9_10595204_2_v1.jpg',
                         '/images/shoes/sneakers/05/AD002AMHLNP9_10595205_3_v1.jpg',
                         '/images/shoes/sneakers/05/AD002AMHLNP9_10595206_4_v1.jpg',],
            price: 10000,
            color: ['черный'],
            sizes: ['40', '42'],
            material: ['Искусственный материал', 'Текстиль'],
            season: 'мульти',
            description: 'Кроссовки выполнены из текстиля и искусственного материала. Классическая шнуровка. Эластичные манжеты голенища. Петля на заднике для удобства надевания. Промежуточная подошва с высоким уровнем амортизации. Специальная рамка из пеноматериала EVA для износостойкости. Технология GORE-TEX: водонепроницаемый прочный и легкий материал, улучшенная вентиляция и дышащая способность.'

        },
        {
            id: '96',
            productName: "Кроссовки KenNIKE AIR VAPORMAX PLUSzo",
            category: 'sneakers',
            imageLinks: ['/images/shoes/sneakers/06/NI464AMHVRD6_10951416_1_v1.jpg',
                         '/images/shoes/sneakers/06/NI464AMHVRD6_10951417_2_v1.jpg',
                         '/images/shoes/sneakers/06/NI464AMHVRD6_10951418_3_v1.jpg',
                         '/images/shoes/sneakers/06/NI464AMHVRD6_10951419_4_v1.jpg',],
            price: 14000,
            color: ['серый'],
            sizes: ['39', '40', '41'],
            material: ['Натуральная  кожа'],
            season: 'мульти',
            description: 'Кроссовки выполнены из текстиля с накладками из искусственного материала. Технология VaporMax Air для невероятной легкости и амортизации. Мягкая ткань и синтетический материал обеспечивают прочность. Резиновые накладки в зонах повышенного износа для дополнительной прочности.'

        },
        {
            id: '97',
            productName: "Кроссовки Marni",
            category: 'sneakers',
            imageLinks: ['/images/shoes/sneakers/07/MA177AMDQHY5_8396422_1_v1.jpg',
                         '/images/shoes/sneakers/07/MA177AMDQHY5_8396423_2_v1.jpg',
                         '/images/shoes/sneakers/07/MA177AMDQHY5_8396424_3_v1.jpg',
                         '/images/shoes/sneakers/07/MA177AMDQHY5_8396425_4_v1.jpg',],
            price: 20000,
            color: ['оранжевый'],
            sizes: ['40'],
            material: ['Текстиль'],
            season: 'демисезон',
            description: 'Кроссовки от премиум-бренда выполнены из текстиля. Особенности: комбинированный дизайн, регулирующая объем шнуровка, подкладка из натуральной кожи, стелька из текстиля.'

        },


    ]


export default PRODUCTS_DATA;
